//
//  CustomDefined.h
//  VPM
//
//  Created by LaiZhaowu on 13-12-6.
//
//

//欢迎页面
#define IS_FIRST_ENTER_HOME_VC @"IS_FIRST_ENTER_HOME_VC"

//RentGalleryViewController
#define HIDDEN_NAVIGATION_BAR @"HIDDEN_NAVIGATION_BAR"



//postRentHouse
#define RENT_YEAR_TEXT @"RENT_YEAR_TEXT"

#define CHANGE_CELL_FRAME @"CHANGE_CELL_FRAME"
#define REFRESH_TABLEVIEW @"REFRESH_TABLEVIEW"


// Setting
#define DEVICE_TOKEN @"DEVICE_TOKEN"
#define IS_AUTO_DOWNLOAD_ON_WWAN @"IS_AUTO_DOWNLOAD_ON_WWAN"
#define IS_DISPLAY_IMAGE_ON_WWAN @"IS_DISPLAY_IMAGE_ON_WWAN"
#define ENABLED_ROMOTE_NOTIFICATION @"ENABLED_ROMOTE_NOTIFICATION"
#define DEFAULT_DISCOUNT_CATEGORY_ID @"DEFAULT_DISCOUNT_CATEGORY_ID"

// Notification
#define FILTER_SIDEBAR_WIDTH 200.0
#define ENABLED_VIEW_DECK_NOTIFICATION @"ENABLED_VIEW_DECK_NOTIFICATION"
#define DISABLED_VIEW_DECK_NOTIFICATION @"DISABLED_VIEW_DECK_NOTIFICATION"
#define OPEN_FILTER_SIDEBR_NOTIFICATION @"OPEN_FILTER_SIDEBR_NOTIFICATION"
#define CLOSE_FILTER_SIDEBR_NOTIFICATION @"CLOSE_FILTER_SIDEBR_NOTIFICATION"
#define FILTER_SIDEBR_OPTION_CHANGED_NOTIFICATION @"FILTER_SIDEBR_OPTION_CHANGED_NOTIFICATION"
#define FILTER_SIDEBR_DID_OPENED_NOTIFICATION @"FILTER_SIDEBR_DID_OPENED_NOTIFICATION"
#define FILTER_SIDEBR_DID_CLOSED_NOTIFICATION @"FILTER_SIDEBR_DID_CLOSED_NOTIFICATION"
#define FILTER_SIDEBR_TYPE_CHANGED_NOTIFICATION @"FILTER_SIDEBR_TYPE_CHANGED_NOTIFICATION"
#define SELECTED_HOME_ITEM_NOTIFICATION @"SELECTED_HOME_ITEM_NOTIFICATION"
#define PUSH_PRODUCT_NOTIFICATION @"PUSH_PRODUCT_NOTIFICATION"


//进入搜索页面的通知
#define FILTER_SIDEBAR_FULL_SCREEN_CHANGED_NOTIFICATION @"FILTER_SIDEBAR_FULL_SCREEN_CHANGED_NOTIFICATION"
#define FILTER_SIDEBAR_NORMAL_SCREEN_CHANGED_NOTIFICATION @"FILTER_SIDEBAR_NORMAL_SCREEN_CHANGED_NOTIFICATION"


// Filter Sidebar
#define FILTER_SIDEBR_TYPE @"FILTER_SIDEBR_TYPE"

// Member
#define MEMBER_ID @"MEMBER_ID"
#define LOGIN_USER_NAME @"LOGIN_USER_NAME"
#define USER_NAME @"USER_NAME"
#define LOGIN_PASSWORD @"LOGIN_PASSWORD"
#define MODIFY_PERSON_INFOMATION @"MODIFY_PERSON_INFOMATION"





